-- Alter employees table to add missing columns for full functionality
USE ehealth;

ALTER TABLE employees
ADD COLUMN other_bank_name VARCHAR(100) AFTER bank_name,
ADD COLUMN person_relationship VARCHAR(50) AFTER person_name,
ADD COLUMN warranty_region VARCHAR(50) AFTER person_relationship,
ADD COLUMN warranty_zone VARCHAR(50) AFTER warranty_region,
ADD COLUMN warranty_email VARCHAR(100) AFTER warranty_kebele,
ADD COLUMN warranty_amount DECIMAL(10,2) AFTER warranty_type,
ADD COLUMN warranty_address TEXT AFTER warranty_amount,
ADD COLUMN warranty_start_date DATE AFTER warranty_address,
ADD COLUMN warranty_end_date DATE AFTER warranty_start_date,
ADD COLUMN warranty_notes TEXT AFTER warranty_end_date,
ADD COLUMN criminal_type VARCHAR(50) AFTER criminal_status,
ADD COLUMN criminal_date DATE AFTER criminal_type,
ADD COLUMN criminal_location VARCHAR(100) AFTER criminal_date,
ADD COLUMN criminal_court VARCHAR(100) AFTER criminal_location,
ADD COLUMN criminal_description TEXT AFTER criminal_court,
ADD COLUMN criminal_sentence TEXT AFTER criminal_description,
ADD COLUMN criminal_status_current VARCHAR(20) AFTER criminal_sentence,
ADD COLUMN criminal_additional_docs VARCHAR(255) AFTER criminal_file,
ADD COLUMN criminal_notes TEXT AFTER criminal_additional_docs,
ADD COLUMN loan_type VARCHAR(50) AFTER loan_status,
ADD COLUMN loan_amount DECIMAL(10,2) AFTER loan_type,
ADD COLUMN loan_lender VARCHAR(100) AFTER loan_amount,
ADD COLUMN loan_account VARCHAR(100) AFTER loan_lender,
ADD COLUMN loan_start_date DATE AFTER loan_account,
ADD COLUMN loan_end_date DATE AFTER loan_start_date,
ADD COLUMN monthly_payment DECIMAL(10,2) AFTER loan_end_date,
ADD COLUMN remaining_balance DECIMAL(10,2) AFTER monthly_payment,
ADD COLUMN loan_status_current VARCHAR(20) AFTER remaining_balance,
ADD COLUMN loan_collateral TEXT AFTER loan_status_current,
ADD COLUMN loan_purpose TEXT AFTER loan_collateral,
ADD COLUMN loan_payment_proof VARCHAR(255) AFTER loan_file,
ADD COLUMN loan_notes TEXT AFTER loan_payment_proof,
ADD COLUMN leave_type VARCHAR(50) AFTER leave_request,
ADD COLUMN leave_duration INT AFTER leave_type,
ADD COLUMN leave_start_date DATE AFTER leave_duration,
ADD COLUMN leave_end_date DATE AFTER leave_start_date,
ADD COLUMN leave_reason TEXT AFTER leave_end_date,
ADD COLUMN leave_contact VARCHAR(100) AFTER leave_reason,
ADD COLUMN leave_supervisor VARCHAR(100) AFTER leave_contact,
ADD COLUMN leave_address TEXT AFTER leave_supervisor,
ADD COLUMN leave_medical_cert VARCHAR(255) AFTER leave_address,
ADD COLUMN leave_supporting_docs VARCHAR(255) AFTER leave_medical_cert,
ADD COLUMN leave_notes TEXT AFTER leave_supporting_docs,
ADD COLUMN language VARCHAR(50) AFTER emergency_contact,
ADD COLUMN other_language VARCHAR(50) AFTER language;

-- Verify
DESCRIBE employees;